services:
  schedule-app:
    build: ./djangoprojectschedule
    ports:
      - "8000:8000"
    volumes:
      - ./djangoprojectschedule:/app

  auth-app:
    build: ./projectschedule_auth
    ports:
      - "8001:8001"
    volumes:
      - ./projectschedule_auth:/app

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/usr/share/nginx/html
  
  # Auth Service Database
  auth_db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - ./projectschedule_auth/.env

  # Resource Service Database
  resource_db:
    image: mariadb:10.11
    ports:
      - "3306:3306"
    env_file:
      - ./djangoprojectschedule/.env