# Generated by Django 5.1 on 2025-09-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectschedule', '0006_workingon_status_alter_developers_row_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingon',
            name='is_relation_active',
            field=models.BooleanField(default=False),
        ),
    ]
